export const REALM_SYMBOL_PROPERTIES = Symbol('REALM_PROPERTIES_SYMBOL');

export const REALM_SYMBOL_SCHEMA = Symbol('REALM_SCHEMA_SYMBOL');

export const REALM_ORIGINAL_VALUE = Symbol('REALM_ORIGINAL_VALUE');
